package SoseL21.generator.templates;

/*Generated by MPS */

import java.util.Map;

@
public class QueriesGenerated extends  {
  public QueriesGenerated() {
    /* error: statement w/o textGen:<no baseMethodDeclaration> */
  }
  public static Object propertyMacro_GetValue_1_0(final  _context) {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  public static Object propertyMacro_GetValue_1_1(final  _context) {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private final Map<String, > pvqMethods = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
  {
    int i = 0;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  @
  @
  public  getPropertyValueQuery(@  identity) {
     query = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return (( != null ?  : super.???()));
  }
  private static class PVQ extends  {
    private final int methodKey;
    /*package*/ PVQ(int methodKey,  property,  templateValue) {
      /* error: statement w/o textGen:<no baseMethodDeclaration> */
      this.??? = ;
    }
    @
    public Object evaluate(@  ctx) throws  {
      switch () {
        case 0:
          return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        case 1:
          return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        default:
          throw <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
      }
    }
  }
  private static final class PROPS {
    /*package*/ static final  name$MnvL = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
}
