package SoseL21.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.baseLanguage.logging.runtime.model.LoggingRuntime;
import org.apache.log4j.Level;
import jetbrains.mps.lang.core.behavior.BaseConcept__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.HashMap;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Reference_Constraints extends BaseConstraintsDescriptor {
  private static final Logger LOG = LogManager.getLogger(Reference_Constraints.class);
  public Reference_Constraints() {
    super(CONCEPTS.Reference$Y7);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.expression$Fe6m, this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_r0uxkx_a0a0a0a0a1a0a0a0c;
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            LoggingRuntime.logMsgView(Level.DEBUG, "vontext node : " + BaseConcept__BehaviorDescriptor.getDetailedPresentation_id22G2W3WJ92t.invoke(_context.getContextNode()), Reference_Constraints.class, null, null);
            LoggingRuntime.logMsgView(Level.DEBUG, "contextNode ancestor: " + BaseConcept__BehaviorDescriptor.getDetailedPresentation_id22G2W3WJ92t.invoke(SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.SoSeWorksheet$tb, false, false)), Reference_Constraints.class, null, null);
            return ListScope.forNamedElements(SNodeOperations.ofConcept(SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.SoSeWorksheet$tb, false, false), LINKS.contents$adPM), CONCEPTS.VariableDeclaration$DC));


          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }
  private static final SNodePointer breakingNode_r0uxkx_a0a0a0a0a1a0a0a0c = new SNodePointer("r:22fa5c38-a13e-4244-be0a-1b45691ce23f(SoseL21.constraints)", "8962575293522686776");

  private static final class CONCEPTS {
    /*package*/ static final SConcept Reference$Y7 = MetaAdapterFactory.getConcept(0xf54c6703341840bcL, 0xbe9312879578d6a1L, 0x782cac11e1965871L, "SoseL21.structure.Reference");
    /*package*/ static final SConcept SoSeWorksheet$tb = MetaAdapterFactory.getConcept(0xf54c6703341840bcL, 0xbe9312879578d6a1L, 0x782cac11e1965857L, "SoseL21.structure.SoSeWorksheet");
    /*package*/ static final SConcept VariableDeclaration$DC = MetaAdapterFactory.getConcept(0xf54c6703341840bcL, 0xbe9312879578d6a1L, 0x58aeb4a19afd5f0aL, "SoseL21.structure.VariableDeclaration");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink expression$Fe6m = MetaAdapterFactory.getReferenceLink(0xf54c6703341840bcL, 0xbe9312879578d6a1L, 0x782cac11e1965871L, 0x1cdc86ac58a14b87L, "expression");
    /*package*/ static final SContainmentLink contents$adPM = MetaAdapterFactory.getContainmentLink(0xf54c6703341840bcL, 0xbe9312879578d6a1L, 0x782cac11e1965857L, 0x782cac11e1965872L, "contents");
  }
}
