package SoseL21.plugin;

/*Generated by MPS */

import com.mbeddr.mpsutil.interpreter.rt.InterpreterEvaluationHelper;
import org.jetbrains.mps.openapi.model.SNode;

public class Evalhelper {

  public static InterpreterEvaluationHelper helper = new InterpreterEvaluationHelper("copl-interpreter");

  public static String eval(SNode n) {
    try {
      Object result = helper.evaluate(n);
      if (result != null) {
        return String.valueOf(result);
      } else {
        return "Null result";
      }
    } catch (Exception e) {
      return "Error";
    }
  }
}
