package SoseL21.generator;

/*Generated by MPS */

import java.util.Collection;

public class Generator extends  {
  public Generator( languageRegistry,  sourceLanguage,  generator) {
    /* error: statement w/o textGen:<no baseMethodDeclaration> */
  }
  @
  @
  public  getModuleReference() {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???("5efffc66-927d-4a41-9639-3d5f4bcbebda(SoseL21.generator)");
  }
  @
  protected void fillTemplateModels( models) {
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  @
  public Collection<> getTargetLanguages() {
    [] rv = new [1];
    [0] = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
}
