package SoseL21.structure;

/*Generated by MPS */


public class ConceptPresentationAspectImpl extends  {
  private  props_BiExpr;
  private  props_Boolean;
  private  props_IStatement;
  private  props_Integer;
  private  props_Number;
  private  props_Reference;
  private  props_SoSeWorksheet;
  private  props_UnnamedInt;
  @
  @
  public  getDescriptor( c) {
     structureDescriptor = () <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    switch (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>) {
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        if ( == null) {
           cpb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
           = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        if ( == null) {
           cpb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
           = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        if ( == null) {
           cpb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
           = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        if ( == null) {
           cpb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
           = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        if ( == null) {
           cpb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
           = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        if ( == null) {
           cpb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
           = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        if ( == null) {
           cpb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
           = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        if ( == null) {
           cpb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
           = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
        return ;
      default:
    }
    return null;
  }
}
