package SoseL21.structure;

/*Generated by MPS */


public final class LanguageConceptSwitch {
  private final  myIndex;
  public static final int BiExpr = 0;
  public static final int Boolean = 1;
  public static final int IStatement = 2;
  public static final int Integer = 3;
  public static final int Number = 4;
  public static final int Reference = 5;
  public static final int SoSeWorksheet = 6;
  public static final int UnnamedInt = 7;
  public LanguageConceptSwitch() {
     builder = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
     = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  /*package*/ int index( cid) {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  public int index( concept) {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
}
