package SoseL21.structure;

/*Generated by MPS */

import java.util.Collection;

public class StructureAspectDescriptor extends  {
  /*package*/ final  myConceptBiExpr = ???();
  /*package*/ final  myConceptBoolean = ???();
  /*package*/ final  myConceptIStatement = ???();
  /*package*/ final  myConceptInteger = ???();
  /*package*/ final  myConceptNumber = ???();
  /*package*/ final  myConceptReference = ???();
  /*package*/ final  myConceptSoSeWorksheet = ???();
  /*package*/ final  myConceptUnnamedInt = ???();
  private final LanguageConceptSwitch myIndexSwitch;
  public StructureAspectDescriptor() {
     = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
  }
  @
  public void reportDependencies( deps) {
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  @
  public Collection<> getDescriptors() {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  @
  @
  public  getDescriptor( id) {
    switch (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>) {
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        return ;
      case <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>:
        return ;
      default:
        return null;
    }
  }
  /*package*/ int internalIndex( c) {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static  createDescriptorForBiExpr() {
     b = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???(-771128172730629956L, -4714404011389167967L, 3601213361451646115L).???(false).???("4087525275905828177").???();
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???(-771128172730629956L, -4714404011389167967L, 3601213361451646115L).???(false).???("4087525275905828181").???();
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static  createDescriptorForBoolean() {
     b = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static  createDescriptorForIStatement() {
     b = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static  createDescriptorForInteger() {
     b = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static  createDescriptorForNumber() {
     b = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???(<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>).???("3601213361451646121").???();
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static  createDescriptorForReference() {
     b = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???(-771128172730629956L, -4714404011389167967L, 8659485376325769311L).???(false).???("2079685202717789063").???();
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static  createDescriptorForSoSeWorksheet() {
     b = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???(-771128172730629956L, -4714404011389167967L, 8659485376325769311L).???(true).???(true).???(true).???("8659485376325769330").???();
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static  createDescriptorForUnnamedInt() {
     b = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
}
