package SoseL21.typesystem;

/*Generated by MPS */


public class singleReference_NonTypesystemRule extends  implements  {
  public singleReference_NonTypesystemRule() {
  }
  public void applyRule(final  soSeWorksheet, final  typeCheckingContext,  status) {
    <> referencs = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???().???() != <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???()) {
      {
        final  errorTarget = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
         _reporter_2309309498 = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      }
    }
  }
  public  getApplicableConcept() {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>;
  }
  public  isApplicableAndPattern( argument) {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
  }
  public boolean overrides() {
    return false;
  }
  private static final class LINKS {
    /*package*/ static final  contents$adPM = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    /*package*/ static final  pointer$Fe6m = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static final class CONCEPTS {
    /*package*/ static final  Reference$Y7 = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    /*package*/ static final  SoSeWorksheet$tb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
}
