package SoseL21.typesystem;

/*Generated by MPS */


public class TypesystemDescriptor extends  {
  public TypesystemDescriptor() {
    {
       nonTypesystemRule = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
      this.???.???();
    }
  }
}
