package SoseL21.constraints;

/*Generated by MPS */


public class ConstraintsAspectDescriptor extends  {
  public ConstraintsAspectDescriptor() {
  }
  @
  public  getConstraints( concept) {
     cncpt = ;
    switch (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>) {
      case 0:
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
      default:
    }
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
  }
  private static final  conceptIndex = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>.???(<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>).???();
}
