package SoseL21.constraints;

/*Generated by MPS */

import java.util.Map;

public class Reference_Constraints extends  {
  public Reference_Constraints() {
    /* error: statement w/o textGen:<no baseMethodDeclaration> */
  }
  @
  protected Map<, > getSpecifiedReferences() {
     d0 = new (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>, this) {
      @
      public boolean hasOwnScopeProvider() {
        return true;
      }
      @
      @
      public  getScopeProvider() {
        return new () {
          @
          public  getSearchScopeValidatorNode() {
            return ;
          }
          @
          public  createScope(final  _context) {
            return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
          }
        };
      }
    };
    <, > references = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return ;
  }
  private static final  breakingNode_r0uxkx_a0a0a0a0a1a0a0a0c = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
  private static final class CONCEPTS {
    /*package*/ static final  Reference$Y7 = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    /*package*/ static final  SoSeWorksheet$tb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    /*package*/ static final  IStatement$Fe = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static final class LINKS {
    /*package*/ static final  pointer$Fe6m = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    /*package*/ static final  contents$adPM = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
}
