package runtime;

/*Generated by MPS */


public class wk2 {

  public static void main(String[] args) {<!TextGen not found for 'SoseL21.structure.VariableDeclaration'!><!TextGen not found for 'SoseL21.structure.VariableDeclaration'!><!TextGen not found for 'SoseL21.structure.ExpressionStatement'!><!TextGen not found for 'SoseL21.structure.ExpressionStatement'!><!TextGen not found for 'SoseL21.structure.ExpressionStatement'!><!TextGen not found for 'SoseL21.structure.VariableDeclaration'!>
  }
}
