package runtime;

/*Generated by MPS */


public class wk2 {

  public static void main(String[] args) {
    int a = 10;
    int b = 10;<!TextGen not found for 'SoseL21.structure.StringLiteral'!>
  }
}
