package SoseL21.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BooleanVariable = 0;
  public static final int IntegerVariable = 1;
  public static final int Reference = 2;
  public static final int Statement = 3;
  public static final int Worksheet = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x34218a42298e4adbL, 0x947448d49415dc43L);
    builder.put(0x180bbddf6e1e9c86L, BooleanVariable);
    builder.put(0x180bbddf6e1e9c59L, IntegerVariable);
    builder.put(0x180bbddf6e1e9cb5L, Reference);
    builder.put(0x180bbddf6e1e9d3cL, Statement);
    builder.put(0x180bbddf6e1e9cddL, Worksheet);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
