package SoseL21.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBiExpr = createDescriptorForBiExpr();
  /*package*/ final ConceptDescriptor myConceptBooleanVariable = createDescriptorForBooleanVariable();
  /*package*/ final ConceptDescriptor myConceptIntegerVariable = createDescriptorForIntegerVariable();
  /*package*/ final ConceptDescriptor myConceptNumber = createDescriptorForNumber();
  /*package*/ final ConceptDescriptor myConceptReference = createDescriptorForReference();
  /*package*/ final ConceptDescriptor myConceptStatement = createDescriptorForStatement();
  /*package*/ final ConceptDescriptor myConceptUnnamedInt = createDescriptorForUnnamedInt();
  /*package*/ final ConceptDescriptor myConceptWorksheet = createDescriptorForWorksheet();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBiExpr, myConceptBooleanVariable, myConceptIntegerVariable, myConceptNumber, myConceptReference, myConceptStatement, myConceptUnnamedInt, myConceptWorksheet);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.BiExpr:
        return myConceptBiExpr;
      case LanguageConceptSwitch.BooleanVariable:
        return myConceptBooleanVariable;
      case LanguageConceptSwitch.IntegerVariable:
        return myConceptIntegerVariable;
      case LanguageConceptSwitch.Number:
        return myConceptNumber;
      case LanguageConceptSwitch.Reference:
        return myConceptReference;
      case LanguageConceptSwitch.Statement:
        return myConceptStatement;
      case LanguageConceptSwitch.UnnamedInt:
        return myConceptUnnamedInt;
      case LanguageConceptSwitch.Worksheet:
        return myConceptWorksheet;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBiExpr() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "BiExpr", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x5513d330c86313aeL);
    b.class_(false, false, false);
    b.super_("SoseL21.structure.Statement", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9d3cL);
    b.origin("r:6c088f79-0555-45e8-b657-8e2cd664ab84(SoseL21.structure)/6130475724255204270");
    b.version(2);
    b.associate("val1", 0x38b9ce94f0cc2551L).target(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x824429996bc02e0L).optional(false).origin("4087525275905828177").done();
    b.associate("val2", 0x38b9ce94f0cc2555L).target(0xf54c6703341840bcL, 0xbe9312879578d6a1L, 0x31fa1478e1b73ca3L).optional(false).origin("4087525275905828181").done();
    b.alias("expr");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBooleanVariable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "BooleanVariable", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9c86L);
    b.class_(false, false, false);
    b.super_("SoseL21.structure.Statement", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9d3cL);
    b.origin("r:6c088f79-0555-45e8-b657-8e2cd664ab84(SoseL21.structure)/1732687248976944262");
    b.version(2);
    b.alias("boolean");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntegerVariable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "IntegerVariable", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9c59L);
    b.class_(false, false, false);
    b.super_("SoseL21.structure.Statement", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9d3cL);
    b.parent(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x824429996bc02e0L);
    b.origin("r:6c088f79-0555-45e8-b657-8e2cd664ab84(SoseL21.structure)/1732687248976944217");
    b.version(2);
    b.alias("int");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNumber() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "Number", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x824429996bc02e0L);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c088f79-0555-45e8-b657-8e2cd664ab84(SoseL21.structure)/586667078891340512");
    b.version(2);
    b.property("value", 0x824429996beb11fL).type(PrimitiveTypeId.INTEGER).origin("586667078891516191").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "Reference", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9cb5L);
    b.class_(false, false, false);
    b.super_("SoseL21.structure.Statement", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9d3cL);
    b.origin("r:6c088f79-0555-45e8-b657-8e2cd664ab84(SoseL21.structure)/1732687248976944309");
    b.version(2);
    b.associate("statement", 0x180bbddf6e203a18L).target(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9d3cL).optional(false).origin("1732687248977050136").done();
    b.alias("ref");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "Statement", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9d3cL);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c088f79-0555-45e8-b657-8e2cd664ab84(SoseL21.structure)/1732687248976944444");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUnnamedInt() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "UnnamedInt", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x824429996b99556L);
    b.class_(false, false, false);
    b.super_("SoseL21.structure.Statement", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9d3cL);
    b.parent(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x824429996bc02e0L);
    b.origin("r:6c088f79-0555-45e8-b657-8e2cd664ab84(SoseL21.structure)/586667078891181398");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWorksheet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SoseL21", "Worksheet", 0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9cddL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c088f79-0555-45e8-b657-8e2cd664ab84(SoseL21.structure)/1732687248976944349");
    b.version(2);
    b.aggregate("statements", 0x180bbddf6e1e9d4dL).target(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9d3cL).optional(true).ordered(true).multiple(true).origin("1732687248976944461").done();
    return b.create();
  }
}
