package SoseL21.editor;

/*Generated by MPS */


/*package*/ class BiExpr_EditorBuilder_a extends  {
  @
  private  myNode;
  public BiExpr_EditorBuilder_a(@  context, @  node) {
    /* error: statement w/o textGen:<no baseMethodDeclaration> */
     = ;
  }
  @
  @
  public  getNode() {
    return ;
  }
  /*package*/  createCell() {
    return ???();
  }
  private  createCollection_0() {
     editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    ???();
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return ;
  }
  private  createRefCell_0() {
    final  referenceLink = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>;
     provider = new (???(), , ???()) {
      protected  createReferenceCell(final  targetNode) {
         cell = ???().???(new <>() {
          public  compute() {
            return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>.???();
          }
        }, , <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>);
        <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        ???(, ???());
        ???();
        return ;
      }
    };
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
     editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!> == null) {
      <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    }
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <> referenceAttributes = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <> currentReferenceAttributes = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???(new <>() {
      public boolean accept( it) {
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      }
    });
    if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???()) {
       manager = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    } else
    return ;
  }
  /*package*/ static class Inline_Builder0 extends  {
    @
    private  myNode;
    private  myReferencingNode;
    /*package*/ Inline_Builder0(@  context,  referencingNode, @  node) {
      /* error: statement w/o textGen:<no baseMethodDeclaration> */
       = ;
       = ;
    }
    /*package*/  createCell() {
      return ???();
    }
    @
    @
    public  getNode() {
      return ;
    }
    private  createProperty_0() {
      ???().???();
      try {
        final  property = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>;
        ???().???(<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>);
         editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        ???();
        <> propertyAttributes = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        <> currentPropertyAttributes = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???(new <>() {
          public boolean accept( it) {
            return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
          }
        });
        if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???()) {
           manager = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
          return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        } else
        return ;
      } finally {
        ???().???();
      }
    }
  }
  private  createConstant_0() {
     editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return ;
  }
  private  createRefCell_1() {
    final  referenceLink = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>;
     provider = new (???(), , ???()) {
      protected  createReferenceCell(final  targetNode) {
         cell = ???().???(new <>() {
          public  compute() {
            return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>.???();
          }
        }, , <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>);
        <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        ???(, ???());
        ???();
        return ;
      }
    };
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
     editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!> == null) {
      <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    }
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <> referenceAttributes = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <> currentReferenceAttributes = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???(new <>() {
      public boolean accept( it) {
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      }
    });
    if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???()) {
       manager = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    } else
    return ;
  }
  /*package*/ static class Inline_Builder1 extends  {
    @
    private  myNode;
    private  myReferencingNode;
    /*package*/ Inline_Builder1(@  context,  referencingNode, @  node) {
      /* error: statement w/o textGen:<no baseMethodDeclaration> */
       = ;
       = ;
    }
    /*package*/  createCell() {
      return ???();
    }
    @
    @
    public  getNode() {
      return ;
    }
    private  createProperty_1() {
      ???().???();
      try {
        final  property = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>;
        ???().???(<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>);
         editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        ???();
        <> propertyAttributes = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        <> currentPropertyAttributes = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???(new <>() {
          public boolean accept( it) {
            return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
          }
        });
        if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???()) {
           manager = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
          return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        } else
        return ;
      } finally {
        ???().???();
      }
    }
  }
  private static final class LINKS {
    /*package*/ static final  val1$wGve = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    /*package*/ static final  val2$wMmB = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static final class CONCEPTS {
    /*package*/ static final  LinkAttribute$v_ = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    /*package*/ static final  PropertyAttribute$Gb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static final class PROPS {
    /*package*/ static final  name$MnvL = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
}
