package SoseL21.editor;

/*Generated by MPS */

import java.util.Collection;

public class EditorAspectDescriptorImpl extends  {
  @
  public Collection<> getDeclaredEditors( concept) {
     cncpt = (() );
    switch (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>) {
      case 0:
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      case 1:
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      case 2:
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      case 3:
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      case 4:
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      case 5:
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      case 6:
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      default:
    }
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static final  conceptIndex = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>.???(<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>, <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>, <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>, <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>, <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>, <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>, <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>).???();
}
