package SoseL21.editor;

/*Generated by MPS */


public class Integer_Editor extends  {
  public  createEditorCell( editorContext,  node) {
    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>.???();
  }
}
