package SoseL21.editor;

/*Generated by MPS */


/*package*/ class SoSeWorksheet_EditorBuilder_a extends  {
  @
  private  myNode;
  public SoSeWorksheet_EditorBuilder_a(@  context, @  node) {
    /* error: statement w/o textGen:<no baseMethodDeclaration> */
     = ;
  }
  @
  @
  public  getNode() {
    return ;
  }
  /*package*/  createCell() {
    return ???();
  }
  private  createCollection_0() {
     editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    ???();
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return ;
  }
  private  createCollection_1() {
     editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
     style = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???();
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return ;
  }
  private  createComponent_0() {
     editorCell = ???().???(, "jetbrains.mps.lang.core.editor.alias");
    return ;
  }
  private  createProperty_0() {
    ???().???();
    try {
      final  property = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>;
      ???().???(<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>);
       editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      ???();
      <> propertyAttributes = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      <> currentPropertyAttributes = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???(new <>() {
        public boolean accept( it) {
          return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
      });
      if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>.???()) {
         manager = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
      } else
      return ;
    } finally {
      ???().???();
    }
  }
  private  createConstant_0() {
     editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return ;
  }
  private  createRefNodeList_0() {
     handler = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
     editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return ;
  }
  private static class contentsListHandler_pqfyti_b0 extends  {
    @
    private  myNode;
    public contentsListHandler_pqfyti_b0( ownerNode,  context) {
      /* error: statement w/o textGen:<no baseMethodDeclaration> */
       = ;
    }
    @
    public  getNode() {
      return ;
    }
    public  getSLink() {
      return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>;
    }
    public  getChildSConcept() {
      return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNameRef'!>;
    }
    public  createNodeCell( elementNode) {
       elementCell = ???().???();
      ???(, , false);
      return ;
    }
    public  createEmptyCell() {
      ???().???();
      ???().???(<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>);
      try {
         emptyCell = null;
         = super.???();
        ???(null, , true);
        ???();
        return ;
      } finally {
        ???().???();
      }
    }
    private static final Object OBJ = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    public void installElementCellActions( elementNode,  elementCell, boolean isEmptyCell) {
      if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!> == null) {
        if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!> == null || <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!> instanceof ) {
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
      }
      if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!> == null) {
        if ( != null) {
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
      }
      if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!> == null) {
        if ( != null) {
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
      }
      if (<!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!> == null) {
        if ( != null) {
          <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
        }
      }
    }
  }
  private  createConstant_1() {
     editorCell = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownNew'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    return ;
  }
  private static final class PROPS {
    /*package*/ static final  name$MnvL = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static final class CONCEPTS {
    /*package*/ static final  PropertyAttribute$Gb = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
    /*package*/ static final  IStatement$Fe = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
  private static final class LINKS {
    /*package*/ static final  contents$adPM = <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.UnknownDotCall'!>;
  }
}
