package SoseL21.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new BiExpr_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new BooleanVariable_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new IntegerVariable_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Number_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Reference_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new UnnamedInt_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Worksheet_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x5513d330c86313aeL), MetaIdFactory.conceptId(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9c86L), MetaIdFactory.conceptId(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9c59L), MetaIdFactory.conceptId(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x824429996bc02e0L), MetaIdFactory.conceptId(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9cb5L), MetaIdFactory.conceptId(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x824429996b99556L), MetaIdFactory.conceptId(0x34218a42298e4adbL, 0x947448d49415dc43L, 0x180bbddf6e1e9cddL)).seal();
}
